theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
cursorline = true
middle-click-paste = true
auto-completion = true
insert-final-newline = false
true-color = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "separator", "file-base-name", "file-modification-indicator", "version-control", "spinner"]
center = ["read-only-indicator", "file-encoding"]
right = ["workspace-diagnostics", "total-line-numbers", "selections", "separator", "position", "position-percentage", "separator", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# C-s = ":w"
C-o = ":open ~/.config/helix/config.toml"
# C-q = ":wq"
# C-e = ":q!"
"C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
